# Generated by Django 6.0.2 on 2026-05-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='Текст жалобы')),
                ('author', models.CharField(default='анонимка', max_length=100, verbose_name='Автор')),
                ('sticker_color', models.CharField(default='#FFF9C4', max_length=20, verbose_name='Цвет стикера')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('is_moderated', models.BooleanField(default=True, verbose_name='Одобрено модерацией')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('faculty', models.CharField(choices=[('writing', 'креативное письмо'), ('rap', '★☆rap studies☆★'), ('design', 'школа дизайна')], max_length=50, verbose_name='Направление')),
                ('portfolio_link', models.URLField(blank=True, null=True, verbose_name='Ссылка на портфолио')),
                ('essay', models.TextField(verbose_name='Эссе')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
