# Generated by Django 6.0.4 on 2026-05-17 05:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_grievance_schoolapplication'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='grievance',
            index=models.Index(fields=['is_moderated', '-created_at'], name='grievance_mod_created_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='post_created_desc_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolapplication',
            index=models.Index(fields=['-submitted_at'], name='application_submitted_desc_idx'),
        ),
    ]
